// AUTO-GENERATED by lib/parser-fs.mjs — DO NOT EDIT.
// Rewritten on every build and every dev start (npm prebuild / predev).
// Lists every child folder of this one that carries _data/index.ts.
import type { WorkspacePageData, CollectionBranch } from '@/lib/collection/types'
import { data as p0 } from './colors/_data'
import { data as p1 } from './fonts/_data'
import { data as p2 } from './shape/_data'
import { data as p3 } from './type/_data'

export const PAGES: WorkspacePageData[] = [p0, p1, p2, p3]

/** Each child together with its own children — see the law in the generator. */
export const TREE: CollectionBranch[] = [
  { page: p0, children: [] },
  { page: p1, children: [] },
  { page: p2, children: [] },
  { page: p3, children: [] },
]
