// AUTO-GENERATED by lib/parser-fs.mjs — DO NOT EDIT.
// Rewritten on every build and every dev start (npm prebuild / predev).
// Lists every child folder of this one that carries _data/index.ts.
import type { WorkspacePageData, CollectionBranch } from '@/lib/collection/types'
import { data as p0 } from './app-config/_data'
import { data as p1 } from './auth/_data'
import { data as p2 } from './blocks/_data'
import { data as p3 } from './build/_data'
import { data as p4 } from './cron/_data'
import { data as p5 } from './data/_data'
import { data as p6 } from './design/_data'
import { data as p7 } from './hosting/_data'
import { data as p8 } from './layouts/_data'
import { data as p9 } from './marketplace/_data'
import { data as p10 } from './passport/_data'
import { data as p11 } from './platform-config/_data'
import { data as p12 } from './testing/_data'
import { data as p13 } from './tools/_data'
import { data as p14 } from './tools-app/_data'
import { PAGES as c0 } from './app-config/_list.generated'
import { PAGES as c2 } from './blocks/_list.generated'
import { PAGES as c3 } from './build/_list.generated'
import { PAGES as c4 } from './cron/_list.generated'
import { PAGES as c6 } from './design/_list.generated'
import { PAGES as c7 } from './hosting/_list.generated'
import { PAGES as c8 } from './layouts/_list.generated'
import { PAGES as c9 } from './marketplace/_list.generated'
import { PAGES as c10 } from './passport/_list.generated'
import { PAGES as c11 } from './platform-config/_list.generated'
import { PAGES as c12 } from './testing/_list.generated'
import { PAGES as c13 } from './tools/_list.generated'
import { PAGES as c14 } from './tools-app/_list.generated'

export const PAGES: WorkspacePageData[] = [p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14]

/** Each child together with its own children — see the law in the generator. */
export const TREE: CollectionBranch[] = [
  { page: p0, children: c0 },
  { page: p1, children: [] },
  { page: p2, children: c2 },
  { page: p3, children: c3 },
  { page: p4, children: c4 },
  { page: p5, children: [] },
  { page: p6, children: c6 },
  { page: p7, children: c7 },
  { page: p8, children: c8 },
  { page: p9, children: c9 },
  { page: p10, children: c10 },
  { page: p11, children: c11 },
  { page: p12, children: c12 },
  { page: p13, children: c13 },
  { page: p14, children: c14 },
]
