// AUTO-GENERATED by lib/parser-fs.mjs — DO NOT EDIT.
// Rewritten on every build and every dev start (npm prebuild / predev).
// Lists every child folder of this one that carries _data/index.ts.
import type { WorkspacePageData, CollectionBranch } from '@/lib/collection/types'
import { data as p0 } from './auth/_data'
import { data as p1 } from './breadcrumbs/_data'
import { data as p2 } from './faq/_data'
import { data as p3 } from './footerPages/_data'
import { data as p4 } from './languageSwitcher/_data'
import { data as p5 } from './offlineCache/_data'
import { data as p6 } from './pwa/_data'
import { data as p7 } from './socials/_data'
import { data as p8 } from './themeToggle/_data'
import { data as p9 } from './topMenu/_data'
import { data as p10 } from './widthToggle/_data'

export const PAGES: WorkspacePageData[] = [p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10]

/** Each child together with its own children — see the law in the generator. */
export const TREE: CollectionBranch[] = [
  { page: p0, children: [] },
  { page: p1, children: [] },
  { page: p2, children: [] },
  { page: p3, children: [] },
  { page: p4, children: [] },
  { page: p5, children: [] },
  { page: p6, children: [] },
  { page: p7, children: [] },
  { page: p8, children: [] },
  { page: p9, children: [] },
  { page: p10, children: [] },
]
